#Copyright (c) 2017 BT Plc (www.btplc.com)
#
#You should have received a copy of the MIT license along with Clew.
#If not, see https://opensource.org/licenses/MIT

config_utils = new.env()

#Functions for checking validity of config.yml
#Eventually this script will be generated by a build script
#so that it can be built based on the known default config from the git repo

#At the moment we do not check validity of values. The config library will fail to load if
#A key does not have a value, so just check all the required key names are in the loaded
#config object will suffice


#Iterates through expected config keys. If any is missing in config.yml
#function returns number of missing key, else 0
#If config.yml does not exist, or is empty, returns -1
config_utils$checkConfig <- function() {
  if(!file.exists("config.yml")) return(-1)
  errlist <- list()
  config.names <- c('mr_jobhist_host_list', 'mr_jobhist_port_list', 'num_clusters', 'cluster_name_list', 'yarn_rm_host_list', 'yarn_rm_port_list', 'mysql_option_group', 'mysql_latency_table_list', 'hive_currentlatency_alert_threshold', 'hive_currentlatency_alert_colour', 'hive_currentlatency_warn_threshold', 'hive_currentlatency_warn_colour', 'hive_currentlatency_ok_colour', 'hive_maxlatency_alert_threshold', 'hive_maxlatency_alert_colour', 'hive_maxlatency_warn_threshold', 'hive_maxlatency_warn_colour', 'hive_maxlatency_ok_colour', 'yarn_apps_pending_alert_threshold', 'yarn_apps_pending_warn_threshold', 'yarn_memreserved_alert_threshold', 'yarn_memreserved_warn_threshold', 'yarn_containers_pending_alert_threshold', 'yarn_containers_pending_warn_threshold', 'yarn_unhealthynodes_alert_threshold', 'yarn_unhealthynodes_warn_threshold', 'yarn_lostnodes_alert_threshold', 'yarn_lostnodes_warn_threshold', 'yarn_alert_colour', 'yarn_warn_colour', 'yarn_ok_colour', 'dashboard_title')
  for(key in config.names) {
    if(is.null(config::get(key))) {
      errlist <- c(errlist,key)
    }
  }
  return(length(errlist))
}


